In [1]:
import numpy as np
from scipy.optimize import differential_evolution
from scipy.optimize import basinhopping

Network class definition

In [3]:
class ACT_reservoir:
    def __init__(self, input_dim, hidden_dim, output_dim, max_iter=20):
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim
        self.max_iter = max_iter
        
        self.total_dim = 1 + input_dim + hidden_dim + output_dim + 1  # Including bias and halting node
        self.W = np.random.uniform(-2, 2, (self.total_dim, self.total_dim))

        # Index ranges for different parts of the state vector
        self.input_indices = range(1, input_dim + 1)
        self.hidden_indices = range(input_dim + 1, input_dim + hidden_dim + 1)
        self.output_indices = range(input_dim + hidden_dim + 1, input_dim + hidden_dim + output_dim + 1)
        self.halting_index = input_dim + hidden_dim + output_dim + 1

    def relu(self,x):
        return np.maximum(0, x)

    def predict(self, xi):
        # Create initial state vector with given input, xi, and set bias unit to 1
        self.x = np.zeros((self.total_dim, 1))
        self.x[0] = 1  # Bias unit
        self.x[self.input_indices] = xi.reshape((self.input_dim, 1))  # Input part

        t = 0
        while t < self.max_iter and self.x[self.halting_index][0] <= 1:
            self.x = self.relu(self.W @ self.x)
            t += 1

        # Extracting and returning the output part of the state vector
        return self.x[self.output_indices],t

    def summary(self):
        print("Total Parameters:", self.total_dim ** 2)  # Since W is a square matrix
        print("Input Dimension:", self.input_dim)
        print("Hidden Dimension:", self.hidden_dim)
        print("Output Dimension:", self.output_dim)
        print("Max Iterations:", self.max_iter)

Example Usage

In [10]:
# Example usage
model = ACT_reservoir(2, 10, 1) 
model.summary()

Total Parameters: 225
Input Dimension: 2
Hidden Dimension: 10
Output Dimension: 1
Max Iterations: 20


In [11]:
# Predict with a sample input
xi = np.array([0.5, 0.7])
output,steps = model.predict(xi)
print("Output:", output)
print("Steps:",steps)

Output: [[3.16135535]]
Steps: 1


Generating data

In [12]:
# Number of samples
num_samples = 1000

# Generate random pairs of integers between 0 and 100
factors = np.random.randint(0, 101, size=(num_samples, 2))

# Compute the product of each pair
products = np.prod(factors, axis=1).reshape(-1, 1, 1)

# Combine factors and products into a single dataset
# Each element in the dataset will be ([factor1, factor2], [[product]])
dataset = [(factors[i].reshape(-1, 1), products[i]) for i in range(num_samples)]

In [13]:
dataset

[(array([[15],
         [ 3]]),
  array([[45]])),
 (array([[58],
         [23]]),
  array([[1334]])),
 (array([[74],
         [47]]),
  array([[3478]])),
 (array([[35],
         [ 4]]),
  array([[140]])),
 (array([[100],
         [  7]]),
  array([[700]])),
 (array([[48],
         [99]]),
  array([[4752]])),
 (array([[26],
         [70]]),
  array([[1820]])),
 (array([[28],
         [78]]),
  array([[2184]])),
 (array([[61],
         [67]]),
  array([[4087]])),
 (array([[ 2],
         [96]]),
  array([[192]])),
 (array([[47],
         [33]]),
  array([[1551]])),
 (array([[71],
         [ 5]]),
  array([[355]])),
 (array([[47],
         [ 8]]),
  array([[376]])),
 (array([[80],
         [58]]),
  array([[4640]])),
 (array([[89],
         [29]]),
  array([[2581]])),
 (array([[62],
         [37]]),
  array([[2294]])),
 (array([[55],
         [80]]),
  array([[4400]])),
 (array([[70],
         [66]]),
  array([[4620]])),
 (array([[59],
         [32]]),
  array([[1888]])),
 (array([[28],
  

Defining fitness function

In [14]:
def fitness(weights, model, train_data, batch_size=5):
    # Reshape the weights and set them in the model
    model.W = weights.reshape(model.W.shape)

    # Randomly sample a batch from the training data
    batch_indices = np.random.choice(len(train_data), batch_size, replace=False)
    batch = [train_data[i] for i in batch_indices]

    total_loss = 0
    for xi, yi in batch:
        predicted_output, _ = model.predict(xi)
        # Assuming a simple mean squared error for the loss
        total_loss += np.mean((predicted_output.flatten() - yi) ** 2)

    return total_loss / len(batch) * 1e-3

In [15]:
model = ACT_reservoir(2, 7, 1)
model.summary()

Total Parameters: 144
Input Dimension: 2
Hidden Dimension: 7
Output Dimension: 1
Max Iterations: 20


Differential Evolution

In [16]:
# Bounds for the weights in the optimization
bounds = [(-4, 4)] * (model.total_dim ** 2)

# Use Differential Evolution with the new fitness function
result = differential_evolution(fitness, bounds, args=(model, dataset, 100), maxiter=100, disp=True,popsize=100,strategy="randtobest1bin")

# Set the optimized weights in the model
optimized_weights = result.x
model.W = optimized_weights.reshape(model.W.shape)

differential_evolution step 1: f(x)= 527.957


Simulated Annealing

In [ ]:
# Initialize your model
model = ACT_reservoir(input_dim=2, hidden_dim=10, output_dim=1, max_iter=20)

# Flatten the initial weights of the model
initial_weights = model.W.flatten()

# Bounds for the weights in the optimization
bounds = [(-2, 2)] * len(initial_weights)

# Define a minimizer_kwargs dictionary for basinhopping
minimizer_kwargs = {"method": "L-BFGS-B", "bounds": bounds, "args": (model, dataset)}

# Use Simulated Annealing to optimize the weights
result = basinhopping(fitness, initial_weights, minimizer_kwargs=minimizer_kwargs, niter=100, disp=True)

# Set the optimized weights in the model
optimized_weights = result.x
model.W = optimized_weights.reshape(model.W.shape)

TESTING/EVALUATION

In [ ]:
# Predict with a sample input
xi = np.array([1,1])
output,steps = model.predict(xi)
print("Output:", output)
print("Steps:",steps)